---
title: "Typology Database Study"
author: Stephanie Evers
output: html_notebook
---

library(randomForest)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(gridExtra)
library(party)
library(edarf)
library(forcats)
library(stats)
library(glmnet)
library(caret)
library(car)
library(lingtypology)
library(rpart)
library(rpart.plot)

#Basic file prep (read file, convert columns in data frame to factors, prep for regression)

df <- read.table("FTSdata.txt", header=TRUE)
names <- colnames(df) #Create a vector of column names
df[,names] <- lapply(df[,names], factor)

drops <- c("ISO") #ISO is a non-binary identifier, not a variable for analysis
df2 <- df[, !(names(df) %in% drops)] 

#Binomial Logistic Regression and variance inflation test

test <- glm(DefArt~., data = df2, family=binomial(link="logit"))
vif(test)
summary(test)

#Random Forest Model
set.seed(45)
model1 <- randomForest(DefArt ~ ., data = df2, ntree = 500, mtry = 4, importance = TRUE)
model1
importance(model1)


#Drop unimportant variables and run again
drops <- c("Topic", "SR")
df2 <- df2[, !names(df2) %in% drops]
model1 <- randomForest(DefArt ~ ., data = df2, ntree = 500, mtry = 4, importance = TRUE)
model1
importance(model1)
varImpPlot(model1)

#Decision Tree

set.seed(45)
tree <- rpart(DefArt ~., data=df2, method="class", minbucket=3, maxdepth=7)
prp(tree, main = "Definite Article Predictors", compress=TRUE, extra=106, box.palette = "auto")

#Language Map
df$ISO <- tolower(df$ISO)
map.feature(lang.iso(df$ISO))




